<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Domain.fs" />
    <Compile Include="Logic.fs" />
    <Compile Include="Persistence.fs" />
    <Compile Include="Words.fs" />
    <Compile Include="WordGame.fs" />
    <Compile Include="MemoryGame.fs" />
    <Compile Include="FoodRoulette.fs" />
    <Compile Include="Audio.fs" />
    <Compile Include="App.fs" />
    <Compile Include="View.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="assets/**/*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.2" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.2" />
    <PackageReference Include="Avalonia.FuncUI" Version="1.5.1" />
    <PackageReference Include="Avalonia.FuncUI.Elmish" Version="1.5.1" />
    <PackageReference Include="Elmish" Version="4.2.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.93.0" />
  </ItemGroup>

</Project>
